language: c
compiler:
  - clang
  - gcc
env:
  - VER=4.0
  - VER=4.1
before_install:
  - git submodule update --init --recursive
  - cd libmaxminddb && ./bootstrap && ./configure && make &&
    sudo make install && cd ..
  - sudo apt-get update
  - sudo apt-get install apt-transport-https python-docutils
  - curl -s https://repo.varnish-cache.org/ubuntu/GPG-key.txt |
    sudo apt-key add -
  - echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-$VER" |
    sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get update
  - sudo apt-get install varnish libvarnishapi-dev libpthread-stubs0-dev
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" VERBOSE=1 distcheck
cache: apt
notifications:
  webhooks:
    urls:
      secure: "BAp2OPYN1sgflZ/c/kDUhhwlEX3I4WvaX2RmorvfPSVUjC5eLEB09Biv1CVyX2GZacECwZL4F8v6YI+i+HU3sPuOLfZxjQLqMp7mlHqZyIRuzhYR3P/mNw789s2dTposRci+0uqJHDSGkurAuAXR5B2R9NK+wkEIUgcqJpGrRn8="
